// flow-typed signature: 37c26cfd9446e523424c40340b5140bf
// flow-typed version: <<STUB>>/react-tabs_v2.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tabs/dist/react-tabs' {
  declare module.exports: any;
}

declare module 'react-tabs/dist/react-tabs.min' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/components/Tab' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/components/TabList' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/components/TabPanel' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/components/Tabs' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/components/UncontrolledTabs' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/helpers/childrenDeepMap' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/helpers/count' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/helpers/elementTypes' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/helpers/propTypes' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/helpers/uuid' {
  declare module.exports: any;
}

declare module 'react-tabs/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tabs/dist/react-tabs.js' {
  declare module.exports: $Exports<'react-tabs/dist/react-tabs'>;
}
declare module 'react-tabs/dist/react-tabs.min.js' {
  declare module.exports: $Exports<'react-tabs/dist/react-tabs.min'>;
}
declare module 'react-tabs/lib/components/Tab.js' {
  declare module.exports: $Exports<'react-tabs/lib/components/Tab'>;
}
declare module 'react-tabs/lib/components/TabList.js' {
  declare module.exports: $Exports<'react-tabs/lib/components/TabList'>;
}
declare module 'react-tabs/lib/components/TabPanel.js' {
  declare module.exports: $Exports<'react-tabs/lib/components/TabPanel'>;
}
declare module 'react-tabs/lib/components/Tabs.js' {
  declare module.exports: $Exports<'react-tabs/lib/components/Tabs'>;
}
declare module 'react-tabs/lib/components/UncontrolledTabs.js' {
  declare module.exports: $Exports<'react-tabs/lib/components/UncontrolledTabs'>;
}
declare module 'react-tabs/lib/helpers/childrenDeepMap.js' {
  declare module.exports: $Exports<'react-tabs/lib/helpers/childrenDeepMap'>;
}
declare module 'react-tabs/lib/helpers/count.js' {
  declare module.exports: $Exports<'react-tabs/lib/helpers/count'>;
}
declare module 'react-tabs/lib/helpers/elementTypes.js' {
  declare module.exports: $Exports<'react-tabs/lib/helpers/elementTypes'>;
}
declare module 'react-tabs/lib/helpers/propTypes.js' {
  declare module.exports: $Exports<'react-tabs/lib/helpers/propTypes'>;
}
declare module 'react-tabs/lib/helpers/uuid.js' {
  declare module.exports: $Exports<'react-tabs/lib/helpers/uuid'>;
}
declare module 'react-tabs/lib/index.js' {
  declare module.exports: $Exports<'react-tabs/lib/index'>;
}
