// flow-typed signature: b21bda85cfde5f424cf58470d4c2b4aa
// flow-typed version: <<STUB>>/react-sidenav_v^2.1.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sidenav'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sidenav' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sidenav/Nav' {
  declare module.exports: any;
}

declare module 'react-sidenav/Nav.test' {
  declare module.exports: any;
}

declare module 'react-sidenav/SideNav' {
  declare module.exports: any;
}

declare module 'react-sidenav/SideNav.test' {
  declare module.exports: any;
}

declare module 'react-sidenav/index.test' {
  declare module.exports: any;
}

declare module 'react-sidenav/withRR4' {
  declare module.exports: any;
}

declare module 'react-sidenav/withRR4.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sidenav/Nav.js' {
  declare module.exports: $Exports<'react-sidenav/Nav'>;
}
declare module 'react-sidenav/Nav.test.js' {
  declare module.exports: $Exports<'react-sidenav/Nav.test'>;
}
declare module 'react-sidenav/SideNav.js' {
  declare module.exports: $Exports<'react-sidenav/SideNav'>;
}
declare module 'react-sidenav/SideNav.test.js' {
  declare module.exports: $Exports<'react-sidenav/SideNav.test'>;
}
declare module 'react-sidenav/index' {
  declare module.exports: $Exports<'react-sidenav'>;
}
declare module 'react-sidenav/index.js' {
  declare module.exports: $Exports<'react-sidenav'>;
}
declare module 'react-sidenav/index.test.js' {
  declare module.exports: $Exports<'react-sidenav/index.test'>;
}
declare module 'react-sidenav/withRR4.js' {
  declare module.exports: $Exports<'react-sidenav/withRR4'>;
}
declare module 'react-sidenav/withRR4.test.js' {
  declare module.exports: $Exports<'react-sidenav/withRR4.test'>;
}
