// flow-typed signature: d04fc2e2a58ebc270920dd6bb2dddd67
// flow-typed version: <<STUB>>/react-json-view_v^1.12.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-json-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-json-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-json-view/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-json-view/dist/main.js' {
  declare module.exports: $Exports<'react-json-view/dist/main'>;
}
