// flow-typed signature: e4407422b8e3833c4bc4549dabf92a41
// flow-typed version: <<STUB>>/react-pager_v^1.3.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pager/demo/bundle' {
  declare module.exports: any;
}

declare module 'react-pager/demo/js/main' {
  declare module.exports: any;
}

declare module 'react-pager/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'react-pager/dist/pager' {
  declare module.exports: any;
}

declare module 'react-pager/karma.conf' {
  declare module.exports: any;
}

declare module 'react-pager/spec/component/pager' {
  declare module.exports: any;
}

declare module 'react-pager/src/pager' {
  declare module.exports: any;
}

declare module 'react-pager/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pager/demo/bundle.js' {
  declare module.exports: $Exports<'react-pager/demo/bundle'>;
}
declare module 'react-pager/demo/js/main.jsx' {
  declare module.exports: $Exports<'react-pager/demo/js/main'>;
}
declare module 'react-pager/demo/webpack.config.js' {
  declare module.exports: $Exports<'react-pager/demo/webpack.config'>;
}
declare module 'react-pager/dist/pager.js' {
  declare module.exports: $Exports<'react-pager/dist/pager'>;
}
declare module 'react-pager/karma.conf.js' {
  declare module.exports: $Exports<'react-pager/karma.conf'>;
}
declare module 'react-pager/spec/component/pager.jsx' {
  declare module.exports: $Exports<'react-pager/spec/component/pager'>;
}
declare module 'react-pager/src/pager.jsx' {
  declare module.exports: $Exports<'react-pager/src/pager'>;
}
declare module 'react-pager/webpack.config.js' {
  declare module.exports: $Exports<'react-pager/webpack.config'>;
}
